name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
      GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}

      PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
      PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      GIT_COMMITER_NAME: GitHub Actions
      GIT_COMMITER_EMAIL: ""
    
    name: Run Semantic Release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npx multi-semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}