name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GIT_COMMITER_NAME: GitHub Actions
      GIT_COMMITER_EMAIL: ""
    
    name: Run Semantic Release
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false 

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npx multi-semantic-release --debug
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}